//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lab2.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...and this is my photo. I am made up, so I can do what I want. At the moment I am standing near the text and smiling..
        /// </summary>
        internal static string About_content_1 {
            get {
                return ResourceManager.GetString("About content 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My favourite activity is impersonating. Right now I am impersonating Jan Kowalski... You will never know who I really am.
        /// </summary>
        internal static string About_content_2 {
            get {
                return ResourceManager.GetString("About content 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My name is Jan Kowalski....
        /// </summary>
        internal static string About_title {
            get {
                return ResourceManager.GetString("About title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to the list.
        /// </summary>
        internal static string Back_to_list {
            get {
                return ResourceManager.GetString("Back to list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        internal static string Birth_date {
            get {
                return ResourceManager.GetString("Birth date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        internal static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book details.
        /// </summary>
        internal static string Book_details {
            get {
                return ResourceManager.GetString("Book details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client details.
        /// </summary>
        internal static string Client_details {
            get {
                return ResourceManager.GetString("Client details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        internal static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create book.
        /// </summary>
        internal static string Create_book {
            get {
                return ResourceManager.GetString("Create book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create client.
        /// </summary>
        internal static string Create_client {
            get {
                return ResourceManager.GetString("Create client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete book.
        /// </summary>
        internal static string Delete_book {
            get {
                return ResourceManager.GetString("Delete book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete client.
        /// </summary>
        internal static string Delete_client {
            get {
                return ResourceManager.GetString("Delete client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit book.
        /// </summary>
        internal static string Edit_book {
            get {
                return ResourceManager.GetString("Edit book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit client.
        /// </summary>
        internal static string Edit_client {
            get {
                return ResourceManager.GetString("Edit client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field required.
        /// </summary>
        internal static string Field_required {
            get {
                return ResourceManager.GetString("Field required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string First_name {
            get {
                return ResourceManager.GetString("First name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future date is not allowed.
        /// </summary>
        internal static string Future_date_not_allowed {
            get {
                return ResourceManager.GetString("Future date not allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date format.
        /// </summary>
        internal static string Invalid_date_format {
            get {
                return ResourceManager.GetString("Invalid date format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is invalid.
        /// </summary>
        internal static string Invalid_email {
            get {
                return ResourceManager.GetString("Invalid email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string Last_name {
            get {
                return ResourceManager.GetString("Last name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about creation of mvc .net core apps.
        /// </summary>
        internal static string Learn_End {
            get {
                return ResourceManager.GetString("Learn End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn.
        /// </summary>
        internal static string Learn_Start {
            get {
                return ResourceManager.GetString("Learn Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string Phone_number {
            get {
                return ResourceManager.GetString("Phone number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string Privacy_Policy {
            get {
                return ResourceManager.GetString("Privacy Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is no privacy policy :).
        /// </summary>
        internal static string Privacy_Policy_Content {
            get {
                return ResourceManager.GetString("Privacy Policy Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date.
        /// </summary>
        internal static string Release_date {
            get {
                return ResourceManager.GetString("Release date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second name.
        /// </summary>
        internal static string Second_name {
            get {
                return ResourceManager.GetString("Second name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text cannot be longer than 30 characters.
        /// </summary>
        internal static string Text_max_30 {
            get {
                return ResourceManager.GetString("Text max 30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text cannot be longer than 50 characters.
        /// </summary>
        internal static string Text_max_50 {
            get {
                return ResourceManager.GetString("Text max 50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text cannot be longer than 60 characters.
        /// </summary>
        internal static string Text_max_60 {
            get {
                return ResourceManager.GetString("Text max 60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed values between 0 and 10.
        /// </summary>
        internal static string Zero_to_ten_allowed {
            get {
                return ResourceManager.GetString("Zero to ten allowed", resourceCulture);
            }
        }
    }
}
